### ISSUE TITLE
Failed at the react-native-decompiler@0.1.0 start script.

### ISSUE THREAD

**Issue by OsamaKamran** [richardfuca/react-native-decompiler#244]
Continuously getting error, after running command: npm start -i index.android.bundle -o ./output
Kindly check below log file..

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '-i',
1 verbose cli   'index.android.bundle',
1 verbose cli   '-o',
1 verbose cli   './output'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-native-decompiler@0.1.0~prestart: react-native-decompiler@0.1.0
6 info lifecycle react-native-decompiler@0.1.0~start: react-native-decompiler@0.1.0
7 verbose lifecycle react-native-decompiler@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-native-decompiler@0.1.0~start: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\HP\Downloads\react-native-decompiler\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\HP\AppData\Local\Programs\Python\Python37\Scripts\;C:\Program Files\Git\cmd;C:\Users\HP\AppData\Local\Programs\Python\Python37;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files (x86)\nodejs\;C:\Users\HP\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\HP\AppData\Local\Programs\Python\Python37\;C:\Users\HP\AppData\Roaming\Microsoft\Windows\Start Menu\Program;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Microsoft Network Monitor 3\;C:\Users\HP\AppData\Local\Programs\Python\P;C:\Program Files (x86)\nodejs\;C:\Users\HP\AppData\Roaming\npm;C:\Users\HP\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\HP\AppData\Local\Android\Sdk\ndk\21.0.6113669\;C:\Program Files\Java\jdk1.8.0_121\bin\;C:\Users\HP\AppData\Local\Programs\Python\Python37\Scripts\pip;C:\Users\HP\AppData\Local\Programs\Python\Python37\Scripts\pip3;C:\Users\HP\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk1.8.0_121\bin\;C:\Users\HP\AppData\Local\Android\Sdk\build-tools\30.0.3\;C:\Users\HP\AppData\Roaming\npm\node_modules\;C:\Users\HP\AppData\Roaming\npm\;
9 verbose lifecycle react-native-decompiler@0.1.0~start: CWD: C:\Users\HP\Downloads\react-native-decompiler
10 silly lifecycle react-native-decompiler@0.1.0~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm i && ts-node ./src/main.ts "index.android.bundle" "./output"'
10 silly lifecycle ]
11 silly lifecycle react-native-decompiler@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle react-native-decompiler@0.1.0~start: Failed to exec start script
13 verbose stack Error: react-native-decompiler@0.1.0 start: `npm i && ts-node ./src/main.ts "index.android.bundle" "./output"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid react-native-decompiler@0.1.0
15 verbose cwd C:\Users\HP\Downloads\react-native-decompiler
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "-i" "index.android.bundle" "-o" "./output"
18 verbose node v12.18.4
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error react-native-decompiler@0.1.0 start: `npm i && ts-node ./src/main.ts "index.android.bundle" "./output"`
22 error Exit status 1
23 error Failed at the react-native-decompiler@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by OsamaKamran** [comment]
@richardfuca please help.

**Comment by richardfuca** [comment]
There was an error in the documentation that has been fixed, please try the updated instructions.
