### ISSUE TITLE
Launch requirements

### ISSUE THREAD

**Issue by onefreddy** [richardfuca/react-native-decompiler#245]
Hi, maybe it good tool,
but i have questions:
1. What are the requirements for the node js version?
2. if Webpack V5 is not supported, how can i make sure my index.android.bundle is not using it?
3. if HERMES/BINARY is not supported, how to determine that I have a wrong bundle?
4. It didn't work for me under Windows. Could you provide an example of running it in the Windows cmd?

**Comment by OsamaKamran** [comment]
Yes, it even did not worked for me! @richardfuca we are waiting very badly for your response, as we need it very much. So kindly reply..

**Comment by richardfuca** [comment]
1. I've tested on Node v14, but it should work on all Node versions that are still supported.
2. Don 't worry about Webpack V5 if you are decompiling a React Native bundle.
3. If you can open the index.android.bundle and see Javascript, it's likely not a Hermes bundle. You can always try decompiling it to see if it works.
4. There was an error in the documentation, which has been fixed. Please try the updated instruction.

**Comment by onefreddy** [comment]
@richardfuca thanks for the answer and the fix. now it runs fine, but unfortunately it gives an error for my bundle as it turned out to be partially binary. Most of it is binary, but somewhere in the middle it contains js code... There is no way to decompile such a bundle? maybe it's just symmetric encryption and a code under it?

[snip]

**Comment by richardfuca** [comment]
I don't have plans to support any binary files. But maybe try this tool, it says it can decompile Hermes. https://github.com/bongtrop/hbctool
